#!/usr/bin/php
<?php

if (count($argv) < 2) {
	echo "You need at least one argument. See man openapp-joomla-detect(1).\n";
	exit(1);
}

define('JPATH_BASE', $argv[1]);

if (!file_exists(JPATH_BASE.'/libraries/joomla/version.php') && !file_exists(JPATH_BASE.'/libraries/cms/version/version.php')) {
	echo "Cannot find Joomla in ".JPATH_BASE."\n";
	exit(1);
}

if (file_exists(JPATH_BASE.'/libraries/joomla/version.php')) {
    include(JPATH_BASE.'/libraries/joomla/version.php');
} else {
    define('_JEXEC', 1);
    include(JPATH_BASE.'/libraries/cms/version/version.php');
}

$version = new JVersion();
$ret = $version->RELEASE.'.'.$version->DEV_LEVEL;

if (!isset($argv[2])) {
	echo "Currently running $ret\n";
	exit(0);
}

$new_version = $argv[2];


if (version_compare($ret, $new_version) == -1) {
	echo "upgrade";
} elseif (version_compare($ret, $new_version) == 0) {
	echo "same";
} elseif (version_compare($ret, $new_version) >= 0) {
	echo "downgrade";
}

?>
